### ISSUE TITLE
Feature request: Add image of schematic

### ISSUE THREAD

**Issue by kyrreaa** [necroware/s7-vrm#1]
Would be great to have an image of schematic in repo as well as the board. Alternatively a pdf.
This way netizens can view it without installing Kicad. Github unfortunately does not have Kicad viewing caopabilities (yet?).
(Also: Wonderfull project! Love the youtube series!)

**Comment by necroware** [comment]
I don't like duplication, because earlier or later such things get diverged and irritate more, than help. I had it already with some projects, so I removed schematics images from everywhere.

**Comment by kyrreaa** [comment]
I always generate it as part of my gerber releases. That way they are archived with the docs for manufacture.

**Comment by necroware** [comment]
Ok, that is a way to do it. I'll add it to the release files.
